In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [7]:
path = r"C:\Users\aboub\Downloads\fish.csv"
data = pd.read_csv(path)

In [16]:
data.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [17]:
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [26]:
data['Species'].unique()
data['Species'].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [28]:
# Dropping "species" independant variable
new_data = data.drop(['Species'],axis=1)
new_data.head()

Weight  Length1  Length2  Length3   Height   Width
0   242.0     23.2     25.4     30.0  11.5200  4.0200
1   290.0     24.0     26.3     31.2  12.4800  4.3056
2   340.0     23.9     26.5     31.1  12.3778  4.6961
3   363.0     26.3     29.0     33.5  12.7300  4.4555
4   430.0     26.5     29.0     34.0  12.4440  5.1340

In [35]:
cols = new_data.shape[1]
y = new_data.iloc[:,0:1]
x = new_data.iloc[:,1:cols]

In [38]:
regression = LinearRegression()

In [39]:
model = regression.fit(x,y)

In [40]:
model.intercept_

array([-499.58695536])

In [41]:
model.coef_

array([[ 62.35521443,  -6.52675249, -29.02621861,  28.29735132,
         22.47330665]])

In [42]:
data.head(1)

Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream   242.0     23.2     25.4     30.0   11.52   4.02

In [44]:
model.predict(x)[0]

array([326.81612777])